apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
  labels:
    app: grafana
    environment: demo
    managed-by: driftguard
type: Opaque
data:
  # echo -n "admin123" | base64
  admin-password: YWRtaW4xMjM= 