apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: driftguard-demo
  labels:
    app: postgres
    environment: demo
    managed-by: driftguard
type: Opaque
data:
  # echo -n "postgres" | base64
  username: cG9zdGdyZXM=
  # echo -n "postgres-password-123" | base64
  password: cG9zdGdyZXMtcGFzc3dvcmQtMTIz 