apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: driftguard-demo
  labels:
    app: postgres
    environment: demo
    managed-by: driftguard
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    name: postgres
  type: ClusterIP 