apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: driftguard-demo
  labels:
    app: redis
    environment: demo
    managed-by: driftguard
type: Opaque
data:
  # echo -n "redis-password-123" | base64
  password: cmVkaXMtcGFzc3dvcmQtMTIz
  # echo -n "redis-user" | base64
  username: cmVkaXMtdXNlcg== 