apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: driftguard-demo
  labels:
    app: redis
    environment: demo
    managed-by: driftguard
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP 