apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: driftguard-demo
  labels:
    app: nginx
    environment: demo
    managed-by: driftguard
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
  environment: "production"
  version: "1.0.0"
  log_level: "info"
  max_connections: "1024"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-env-config
  namespace: driftguard-demo
  labels:
    app: nginx
    environment: demo
    managed-by: driftguard
data:
  NGINX_ENV: "production"
  LOG_LEVEL: "info"
  NGINX_PORT: "80"
  WORKER_PROCESSES: "auto"
  WORKER_CONNECTIONS: "1024" 