apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: driftguard-demo
  labels:
    app: nginx
    environment: demo
    managed-by: driftguard
type: Opaque
data:
  # These are base64 encoded values - in real scenarios, use proper secret management
  # echo -n "admin" | base64
  username: YWRtaW4=
  # echo -n "password123" | base64
  password: cGFzc3dvcmQxMjM=
  # echo -n "nginx-secret-key" | base64
  api-key: bmdpbngtc2VjcmV0LWtleQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-tls-secret
  namespace: driftguard-demo
  labels:
    app: nginx
    environment: demo
    managed-by: driftguard
type: kubernetes.io/tls
data:
  # These are placeholder values - replace with actual TLS certificates
  # echo -n "tls-cert-content" | base64
  tls.crt: dGxzLWNlcnQtY29udGVudA==
  # echo -n "tls-key-content" | base64
  tls.key: dGxzLWtleS1jb250ZW50 