apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: driftguard-demo
  labels:
    app: nginx
    environment: demo
    managed-by: driftguard
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  namespace: driftguard-demo
  labels:
    app: nginx
    environment: demo
    managed-by: driftguard
    type: external
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  type: NodePort 